swagger: "2.0"
info:
  title: ToDoAPI
  version: 1.0.11
schemes:
    - "http"
    - "https"
paths:
  /todo/create:
    post:
      tags:
        - create todo
      summary: Create todo
      operationId: createToDo
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: ToDoRequest
          schema:
            $ref: "#/definitions/ToDoRequest"
          required: true  
      responses:
        "201":
          description: ToDo created
          schema:
            $ref: "#/definitions/ToDoResponse"
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
  /todos:
    get:
      tags:
        - todos
      summary: Get all  todos  
      operationId: getToDos
      produces:
        - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: "#/definitions/ToDoResponse"
        "404":
          description: ToDos not exists
        "500":
          description: Internal Server Error
  /todo/{todoID}:
    parametres:
    - in:  path
      name: todoID
      type: integer
      format: uint64
      required: true
    get:
      tags:
        - todo
      operationId: getToDo
      summary: Get todo 
      produces:
        - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: "#/definitions/ToDoResponse"
        "404":
          description: ToDo not exists
        "500":
          description: Internal Server Error
    patch:
      tags:
        - todo
      operationId: patchToDo
      summary: Patch todo
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: PatchToDoRequest
          schema:
            $ref: "#/definitions/ToDoPatchRequest"
      responses:
        "201":
          description: ToDo updated
          schema:
            $ref: "#/definitions/ToDoResponse"
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
    delete:
      tags:
        - todo
      operationId: deleteToDo
      summary: Delete todo
      description: Delete ToDo
      responses:
        "204":
          description: ToDo deleted
        "404":
          description: Not Found
        "500":
          description: Internal Server Error  
definitions:
    ToDoRequest:
      type: object
      properties:
        description:
          type: string
        status:
          type: string 
          required: ["description","status"]
    ToDoResponse:
      type: object
      properties:
        id:
          type: integer
          format: uint64
        description:
          type: string
        status:
          type: string 
        created_at:
          type: string
          format: date
        updated_at:
          type: string
          format: date
        deleted_at:
          type: string
          format: date  
    ToDoPatchRequest:
      type: object
      properties:
        description:
          type: string
        status:
          type: string