CREATE TABLE to_dos (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "description " TEXT  NOT NULL, 
  "status" varchar(100) NOT NULL DEFAULT, 
  "created_at" TIMESTAMP NOT NULL DEFAULT (now()), 
  "updated_at" TIMESTAMP NOT NULL DEFAULT (now()),
  "deleted_at"   TIMESTAMP
);