CREATE TABLE marketplaces (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "description " varchar(100) NOT NULL, 
  "status" varchar(100) NOT NULL DEFAULT, 
  "created_at" TIMESTAMPTZ NOT NULL DEFAULT (now()), 
  "updated_at" TIMESTAMPTZ NOT NULL DEFAULT (now()),
  "deleted_at"   TIMESTAMPTZ
);