CREATE TABLE users (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "name" TEXT  NOT NULL,
  "email" TEXT NOT NULL  UNIQUE,
  "password" TEXT NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT (now()), 
  "updated_at" TIMESTAMP NOT NULL DEFAULT (now()),
  "deleted_at"   TIMESTAMP
);

CREATE TABLE to_dos (
  "id" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  "description" TEXT  NOT NULL,
  "status" TEXT NOT NULL,
  "user_id" INT, 
  "created_at" TIMESTAMP NOT NULL DEFAULT (now()), 
  "updated_at" TIMESTAMP NOT NULL DEFAULT (now()),
  "deleted_at"   TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE
);